"""Tests for triangular dislocation functions (tdcalc).

Tests are validated against reference data generated by the original Matlab
implementation of Nikkhoo & Walter (2015). Four configurations are tested:
full-space simple/complex and half-space simple/complex.
"""

from pathlib import Path

import numpy as np
import pytest

from geodef import tri as tdcalc

# Use ~100-point subset for fast tests (every 10th point from 1000)
_SUBSET_STRIDE = 10
_REF_DATA_DIR = Path(__file__).parent / "reference_data"


def _load_reference(name: str) -> dict[str, np.ndarray]:
    """Load a reference .npz file by stem name."""
    return dict(np.load(str(_REF_DATA_DIR / f"{name}.npz")))


@pytest.fixture(
    params=["FS_simple", "FS_complex", "HS_simple", "HS_complex"],
)
def ref_config(request: pytest.FixtureRequest) -> dict[str, np.ndarray]:
    """Load reference data for each tdcalc test configuration."""
    return {"name": request.param, **_load_reference(request.param)}


def _get_disp_func(name: str):
    """Return the appropriate displacement function for a given config."""
    if name.startswith("FS"):
        return tdcalc.TDdispFS
    return tdcalc.TDdispHS


def _get_strain_func(name: str):
    """Return the appropriate strain function for a given config."""
    if name.startswith("FS"):
        return tdcalc.TDstrainFS
    return tdcalc.TDstrainHS


class TestTDcalcDisplacement:
    """Test displacement calculations against Matlab reference data."""

    def test_displacement_matches_reference(self, ref_config: dict) -> None:
        """Displacement output should match Matlab reference values."""
        name = ref_config["name"]
        obs = ref_config["obs"][::_SUBSET_STRIDE]
        tri = ref_config["tri"].astype(float)
        slip = ref_config["slip"].astype(float)
        nu = float(ref_config["nu"])
        disp_func = _get_disp_func(name)

        disp = disp_func(obs, tri, slip, nu)

        ref_ue = ref_config["UEf"][::_SUBSET_STRIDE]
        ref_un = ref_config["UNf"][::_SUBSET_STRIDE]
        ref_uv = ref_config["UVf"][::_SUBSET_STRIDE]

        np.testing.assert_almost_equal(disp[:, 0], ref_ue)
        np.testing.assert_almost_equal(disp[:, 1], ref_un)
        np.testing.assert_almost_equal(disp[:, 2], ref_uv)


class TestTDcalcStrain:
    """Test strain calculations against Matlab reference data."""

    def test_strain_matches_reference(self, ref_config: dict) -> None:
        """Strain output should match Matlab reference values."""
        name = ref_config["name"]
        obs = ref_config["obs"][::_SUBSET_STRIDE]
        tri = ref_config["tri"].astype(float)
        slip = ref_config["slip"].astype(float)
        nu = float(ref_config["nu"])
        strain_func = _get_strain_func(name)

        strain = strain_func(obs, tri, slip, nu).T
        ref_strain = ref_config["Strain"][::_SUBSET_STRIDE, :].T

        np.testing.assert_almost_equal(strain, ref_strain)


class TestTDcalcProperties:
    """Test physical properties of the triangular dislocation solution."""

    def test_zero_slip_gives_zero(self) -> None:
        """Zero slip should produce zero displacement."""
        obs = np.array([[1.0, 1.0, -1.0], [2.0, 3.0, -2.0]])
        tri = np.array([[0.0, 0.0, -1.0], [1.0, 0.0, -1.0], [0.0, 1.0, -1.0]])
        slip = np.array([0.0, 0.0, 0.0])

        disp = tdcalc.TDdispHS(obs, tri, slip, 0.25)
        np.testing.assert_allclose(disp, 0.0, atol=1e-15)

    def test_linearity(self) -> None:
        """Doubling slip should double displacement (linear elasticity)."""
        obs = np.array([[2.0, 2.0, 0.0], [3.0, 1.0, 0.0]])
        tri = np.array([[0.0, 0.0, -2.0], [2.0, 0.0, -2.0], [1.0, 2.0, -3.0]])
        slip1 = np.array([1.0, 0.5, 0.0])
        slip2 = np.array([2.0, 1.0, 0.0])

        disp1 = tdcalc.TDdispHS(obs, tri, slip1, 0.25)
        disp2 = tdcalc.TDdispHS(obs, tri, slip2, 0.25)
        np.testing.assert_allclose(disp2, 2 * disp1, rtol=1e-12)

    def test_displacement_decays_with_distance(self) -> None:
        """Displacement should decrease far from the source."""
        tri = np.array([[0.0, 0.0, -2.0], [2.0, 0.0, -2.0], [1.0, 2.0, -3.0]])
        slip = np.array([1.0, 0.0, 0.0])

        obs_near = np.array([[1.0, 1.0, 0.0]])
        obs_far = np.array([[50.0, 50.0, 0.0]])
        disp_near = tdcalc.TDdispHS(obs_near, tri, slip, 0.25)
        disp_far = tdcalc.TDdispHS(obs_far, tri, slip, 0.25)

        mag_near = np.linalg.norm(disp_near)
        mag_far = np.linalg.norm(disp_far)
        assert mag_near > mag_far

    def test_fs_vs_hs_deep_source(self) -> None:
        """For deep sources and obs at depth, HS should approach FS.

        When both the source and observation point are far from the free
        surface, the image source contribution is negligible.
        """
        obs = np.array([[1.0, 1.0, -100.0]])
        tri = np.array([
            [0.0, 0.0, -100.0],
            [1.0, 0.0, -100.0],
            [0.0, 1.0, -101.0],
        ])
        slip = np.array([1.0, 0.0, 0.0])

        disp_fs = tdcalc.TDdispFS(obs, tri, slip, 0.25)
        disp_hs = tdcalc.TDdispHS(obs, tri, slip, 0.25)

        np.testing.assert_allclose(disp_hs, disp_fs, rtol=1e-3)
